llm:
  type: demystifygraphrag.typing.LlmLoadingParams
  # model_path: '/home/bens/projects/DemystifyGraphRAG/models/gemma-2-9b-it-IQ4_XS.gguf'
  model_path: '/home/bens/projects/DemystifyGraphRAG/models/gemma-2-2b-it-Q4_K_M.gguf'
  tokenizer_URI: 'google/gemma-2-9b-it'
preprocess:
  type: demystifygraphrag.typing.PreprocessParams
  raw_documents:
    type: demystifygraphrag.typing.RawDocumentsParams
    raw_documents_folder: /home/bens/projects/DemystifyGraphRAG/data/01_raw/machine_learning_intro
    raw_content_column: 'content'
  chunk:
    type: demystifygraphrag.typing.ChunkParams
    window_size: 300
    overlap: 100
    column_to_chunk: 'content'
    results_column: 'chunk'
entity_extraction:
  type: demystifygraphrag.typing.EntityExtractionParams
  max_gleans: 5
  column_to_extract: 'chunk'
  results_column: 'raw_entities'
entity_extraction_prompt:
  type: demystifygraphrag.typing.EntityExtractionPromptParams
  prompts:
    type: demystifygraphrag.typing.EntityExtractionPrompts
    # These should't be defined here since the prompt can get large and make this file unreadable
    # Values should rather  be passed from a node or left empty, in which case default prompts are used
    # 
    # entity_extraction_prompt: str
    # continue_prompt: str
    # loop_prompt: str
  formatting:
    type: demystifygraphrag.typing.EntityExtractionPromptFormatting
    tuple_delimiter: "<|>"
    record_delimiter: "##"
    completion_delimiter: "<|COMPLETE|>"
    entity_types: ["organization", "person", "geo", "event"]
raw_entities_to_graph:
  type: demystifygraphrag.typing.RawEntitiesToGraphParams
  raw_entities_column: 'raw_entities'
  reference_column: 'chunk_id'
  feature_delimiter: "\n" # When the same node or edge is found multiple times, features are concatenated using this demiliter
summarize_descriptions:
  type: demystifygraphrag.typing.DescriptionSummarizationParams
  max_input_tokens: 4000
  max_output_tokens: 500
  feature_delimiter: "\n"  # Used to 'un-cocatenate' descriptions. When the same node or edge was found multiple times, features were concatenated using this demiliter
summarize_descriptions_prompt:
  type: demystifygraphrag.typing.DescriptionSummarizationPromptParams
  # The prompt should't be defined here since it can get large and make this file unreadable
  # It should rather  be passed from a node or left empty, in which case default prompt is used
  # prompt: str
  formatting:
    type: demystifygraphrag.typing.DescriptionSummarizationPromptFormatting
    entity_name: null  # This comes from the entity extraction
    description_list: null  # This comes from the entity extraction
